# Generated by Django 4.2.5 on 2023-09-28 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rants", "0002_rant_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rant",
            name="likes",
        ),
        migrations.AddField(
            model_name="rant",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rants.rant")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "rant")},
            },
        ),
    ]
