# Generated by Django 4.2.5 on 2023-09-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rants", "0003_remove_rant_likes_rant_likes_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="rant",
            name="image",
            field=models.ImageField(blank=True, default=None, null=True, upload_to="rants/images/"),
        ),
    ]
