# Generated by Django 4.2.5 on 2023-09-30 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rants", "0005_delete_like"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rant",
            options={"ordering": ["-created"], "verbose_name": "rant", "verbose_name_plural": "rants"},
        ),
    ]
