# Generated by Django 4.2.5 on 2023-10-21 11:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rants", "0007_rename_uuid_rant_uid_alter_rant_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rant",
            old_name="uid",
            new_name="uuid",
        ),
        migrations.AlterField(
            model_name="rant",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="uuid"),
        ),
    ]
