# Generated by Django 5.1.2 on 2024-11-25 08:05

import autoslug.fields
import django.db.models.deletion
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rants", "0012_alter_rant_popularity_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rant",
            options={"ordering": ["-created"], "verbose_name": "rant", "verbose_name_plural": "rants"},
        ),
        migrations.AlterField(
            model_name="rant",
            name="image",
            field=models.ImageField(blank=True, default=None, null=True, upload_to="rants/images/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="rant",
            name="likes",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="rant",
            name="popularity_score",
            field=models.DecimalField(db_index=True, decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="rant",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="uuid", unique=True),
        ),
        migrations.AlterField(
            model_name="rant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="rants", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="rant",
            name="uuid",
            field=model_utils.fields.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="rant",
            index=models.Index(fields=["-popularity_score", "-created"], name="rants_rant_popular_41af0b_idx"),
        ),
        migrations.AddIndex(
            model_name="rant",
            index=models.Index(fields=["-created"], name="rants_rant_created_0529db_idx"),
        ),
        migrations.AddIndex(
            model_name="rant",
            index=models.Index(fields=["user", "-created"], name="rants_rant_user_id_df5d69_idx"),
        ),
    ]
