# Generated by Django 5.1.2 on 2024-12-17 06:52

import utils.image_resizer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rants", "0013_alter_rant_options_alter_rant_image_alter_rant_likes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rant",
            options={
                "ordering": ["-popularity_score", "-created"],
                "verbose_name": "rant",
                "verbose_name_plural": "rants",
            },
        ),
        migrations.AlterField(
            model_name="rant",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="rants/images/%Y/%m/",
                validators=[utils.image_resizer.validate_rectangular_image],
            ),
        ),
    ]
