# Generated by Django 5.1.2 on 2024-12-21 04:51

import rantr.utils.image_resizer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rants", "0014_alter_rant_options_alter_rant_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rant",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="rants/images/%Y/%m/",
                validators=[rantr.utils.image_resizer.validate_rectangular_image],
            ),
        ),
    ]
