# Generated by Django 4.2.5 on 2023-10-03 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(related_name="followers", to=settings.AUTH_USER_MODEL),
        ),
    ]
