# Generated by Django 4.2.5 on 2023-10-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_name_user_first_name_user_is_onboarded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, default=None, null=True, upload_to="users/profile_picture/"),
        ),
    ]
