# Generated by Django 4.2.5 on 2023-10-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_location_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(default="", max_length=250),
        ),
    ]
