# Generated by Django 5.1.2 on 2024-11-25 08:05

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0005_user_bio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-date_joined"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, default="", help_text="Tell us about yourself in 250 characters or less", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(db_index=True, related_name="followers", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(
                blank=True, default="", help_text="City, Country or any location identifier", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, default=None, null=True, upload_to="users/profile_picture/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True,
                error_messages={"unique": "A user with that username already exists."},
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters.",
                        regex="^[\\w.@+-]+$",
                    )
                ],
                verbose_name="username",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_user_usernam_65d164_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_onboarded"], name="users_user_is_onbo_b15ec7_idx"),
        ),
    ]
