# Generated by Django 4.2.9 on 2024-10-30 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rants", "0012_alter_rant_popularity_score"),
        ("comments", "0002_comment_created_comment_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="rant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="rants.rant"
            ),
        ),
    ]
