# Generated by Django 4.2.5 on 2023-11-11 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_remove_message_id_message_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="timestamp",
        ),
    ]
