# Generated by Django 4.2.5 on 2023-11-12 10:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0003_remove_message_timestamp"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Message",
            new_name="DirectMessage",
        ),
    ]
