# Generated by Django 5.1.2 on 2024-11-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="conversation",
            table=None,
        ),
        migrations.AlterModelTable(
            name="message",
            table=None,
        ),
    ]
